### ISSUE TITLE
June July tasks 

### ISSUE THREAD

**Issue by cartazio** [anarchy-ai/LLM-VM#24]
Tasks for end of June and through July 2023

### Error handling 
   
- [x]  Can cleanup in progress fine tunings when ctrl+c abort the local version of LLM-VM  https://github.com/anarchy-ai/LLM-VM/pull/23  

- [x] Can retry data synthesis when given malformed json results  https://github.com/anarchy-ai/LLM-VM/pull/23
 - [x] Maybe later should consider a more robust encoding rather than json, where mismatched brackets from unquoted responses  https://github.com/anarchy-ai/LLM-VM/issues/29

## Agents
 - [x] Get REBEL agent onto main branch LLM-VM/main https://github.com/anarchy-ai/LLM-VM/issues/2
 - [x] Get Backward Chaining agent onto main branch  LLM-VM/main https://github.com/anarchy-ai/LLM-VM/issues/2
 - [x] Get all agents to use the optimizer endpoint, as opposed to the openai api https://github.com/anarchy-ai/LLM-VM/issues/19
- [x] Get Flat agent on LLM-VM/main https://github.com/anarchy-ai/LLM-VM/issues/2
- [x] Agent test suite https://github.com/anarchy-ai/LLM-VM/issues/20

## Documentation
  - [x] Write documentation for LLM-VM on docusaurus.    https://github.com/anarchy-ai/LLM-VM/issues/22

## Data Synthesis https://github.com/anarchy-ai/LLM-VM/issues/3
 - [x] Add all the parameters 
 - [x] choose a more robust encoding for question answer response sets https://github.com/anarchy-ai/LLM-VM/issues/29
 - [x] K-shot support
 - [ ] Prompt variation aka support alternative prompts, possibly with different defaults for each supported model
 - [x] Track number of actual responses vs requested
 - [x] Dedup handling
    -    - [x] First exact repeat parameters
    -  - [x] then semantic vector comparisons? 
 - [ ] Parameterize the diverse ways you might want to define exact matches or vector comparisions

## Parameter Management
 - [ ] Documenting all the parameters and making sure they’re sane https://github.com/anarchy-ai/LLM-VM/issues/25

## Instrumentation / Statistics
- [ ] Keep track of detailed information about inference, data synthesis, response sizes, latency, quality #26

## Inference Determinism (more long term question,not immediate prioriity)
- [x] What LLM flavors have explicit rng Seed being surfaces as optional input or something that can be part of the response metadata for reproducibility? #27

## misc
- [ ] Maybe also something about managing/tracking fine tunings you’ve generated https://github.com/anarchy-ai/LLM-VM/issues/28

**Comment by shivance** [comment]
Hi I'm interested in contributing to Anarchy, but I'm new here ! Where can I contribute?

**Comment by cartazio** [comment]
Hey @shivance, I think the best way for us to figure that out is to introduce yourself on the discord and we’ll help pick out a good first ticket!

**Comment by cartazio** [comment]
@abhigya-sodani  whats left for the agents task items

**Comment by abhigya-sodani** [comment]
@cartazio we should close this and make a new tracker for August/September

**Comment by cartazio** [comment]
yeah sounds good
