### ISSUE TITLE
Architecture Overview & Roadmap

### ISSUE THREAD

**Issue by mmirman** [anarchy-ai/LLM-VM#277]
[High-Level Architecture Overview](https://docs.google.com/drawings/d/1TxRxJ7Amy449dvnFgOrnqofX3SfkLD3qqqKXEAfRHsE/edit?usp=sharing)

- [x] **Implicit Agents 🔧🕵️:** *The Anarchy LLM-VM can be set up to use external tools through our agents such as **REBEL** just by supplying tool descriptions!*

- [ ] **Inference Optimization 🚄:** *The Anarchy LLM-VM is optimized from the agent level all the way to assembly on known LLM architectures to get the most bang for your buck. With state-of-the-art batching, sparse inference and quantization, distillation, and multi-level colocation, we aim to provide the fastest framework available.*

- [ ] **Task Auto-Optimization 🚅:** *The Anarchy LLM-VM will analyze your use cases for repetitive tasks where it can activate student-teacher distillation to train a super-efficient small model from a larger more general model without losing accuracy.  It can furthermore take advantage of data-synthesis techniques to improve results.*

- [x] **Library Callable 📚:** *We provide a library that can be used from any Python codebase directly.*

- [ ] **HTTP Endpoints 🕸️:** *We provide an HTTP standalone server to handle completion requests.*

- [ ] **Live Data Augmentation 📊:* *You will be able to provide a live updating data set and the Anarchy LLM-VM will **fine-tune** your models or work with a **vector DB** to provide up-to-date information with citations*

- [ ] **Web Playground 🛝:** *You will be able to run the Anarchy LLM-VM and test its outputs from the browser.*

- [ ] **Load-Balancing and Orchestration ⚖️:** *If you have multiple LLMs or providers you'd like to utilize, you will be able to hand them to the Anarchy LLM-VM to automatically figure out which to work with and when to optimize your uptime or your costs*

- [x] **Output Templating 🤵:** *You can ensure that the LLM only outputs data in specific formats and fills in variables from a template with either regular expressions, LMQL, or OpenAI's template language*

- [ ] **Persistent Stateful Memory 📝:**  *The Anarchy LLM-VM can remember a user's conversation history and react accordingly*

**Comment by mmirman** [comment]
Note:  Some of these have existing issues attached to them!  This needs cleanup and organization (this is high-priority).

**Comment by Avr-Arnold** [comment]
I think that some features build on others. For example, Output Templating can depend on Persistent Stateful Memory by remembering the template. I have used LangChain and the way they do their templating is by injecting it into the users input as a header for every call. Having Memory can eliminate this. Additionally, the backtracking can also be extended to the Persistent State not just outputs. In conclusion, I believe Persistent Stateful Memory should go before Output Templating and perhaps at the same time as backtracking.

**Comment by mmirman** [comment]
> the way they do their templating is by injecting it into the users input as a header for every call

We want strong guarantees with our templating.  The ability to sampling constrained by regex for example

**Comment by VictorOdede** [comment]
Short Term LLM-VM Roadmap

<img width="3597" alt="LLM-VM" src="https://github.com/anarchy-ai/LLM-VM/assets/17176393/6077cf08-7f33-4b29-81bf-3626106a6d19">
